workflows:
  ios-workflow:
    name: iOS Build (Unsigned)
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - name: Fetch Flutter dependencies
        script: |
          flutter pub get
      - name: Build iOS App (Unsigned)
        script: |
          # builds the release iOS app without code signing
          flutter build ipa --release --no-codesign
      - name: Package App Bundle into Zip
        script: |
          cd build/ios/iphoneos
          zip -r Runner.zip Runner.app
    artifacts:
      - build/ios/iphoneos/*.zip
      - build/ios/ipa/*.ipa
